"""Utility functions for analyzing Insider Store T&D prioritization outputs.

Expected inputs
---------------
1. Executive product-level dataframe generated by:
   02_td_farol_executivo_produto.sql
2. Optional analytical dataframe generated by:
   01_td_base_analitica_item_reversa_tag.sql

The functions are intentionally pandas-only and side-effect free, so they can be
used in notebooks, scripts, Streamlit, or scheduled checks.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Mapping, Sequence

import numpy as np
import pandas as pd


EXECUTIVE_REQUIRED_COLUMNS = {
    "product_name",
    "category",
    "sinal_priorizacao",
    "priority_score",
    "td_score",
    "commercial_score",
    "qt_items_vendidos",
    "receita_liquida",
    "qt_items_returned",
    "td_rate",
    "td_rate_categoria",
    "delta_vs_categoria",
}

ANALYTICAL_REQUIRED_COLUMNS = {
    "order_name",
    "sku",
    "product_name",
    "category",
    "color",
    "size",
    "tipo_problema",
    "problema_tag",
    "client_comment",
    "qt_items_returned",
}


@dataclass(frozen=True)
class PrioritizationThresholds:
    """Thresholds used to classify products in Python.

    Keep these aligned with the SQL params and CASE statement unless you are
    deliberately running a sensitivity analysis.
    """

    min_items_vendidos: int = 30
    min_items_returned: int = 5
    td_score_prioritize: float = 0.70
    commercial_score_prioritize: float = 0.60
    commercial_score_alert: float = 0.70
    td_score_alert_min: float = 0.50
    low_td_score: float = 0.50
    low_commercial_score: float = 0.40


# ---------------------------------------------------------------------------
# Tag → action type mapping
# ---------------------------------------------------------------------------

TAG_TO_ACTION: dict[str, str] = {
    # Modelagem
    "caimento_ruim": "Modelagem",
    "modelagem_ruim": "Modelagem",
    "sustentacao_ruim": "Modelagem",
    # Grade
    "comprimento_curto": "Grade",
    "comprimento_longo": "Grade",
    "tamanho_grande": "Grade",
    "tamanho_pequeno": "Grade",
    "tamanho_pepequeno": "Grade",
    # Tecido
    "tecido_fino": "Tecido",
    "tecido_grosso": "Tecido",
    "tecido_transparente": "Tecido",
    "tecido_qualidade_ruim": "Tecido",
    "tecido_marca_corpo": "Tecido",
    "tecido_quente": "Tecido",
    "tecido_amassa": "Tecido",
    "pilling_bolinhas": "Tecido",
    "encolhimento": "Tecido",
    # Defeito → Investigação adicional
    "defeito_costura": "Investigação adicional",
    "defeito_aviamento": "Investigação adicional",
    "defeito_fio_puxado": "Investigação adicional",
    "defeito_furo_rasgo": "Investigação adicional",
    "defeito_gola": "Investigação adicional",
    "defeito_mancha": "Investigação adicional",
    # Ambíguo → Investigação adicional
    "conforto_negativo": "Investigação adicional",
    # Comunicação
    "cor_diferente_site": "PDP/Comunicação",
}

POSITIVE_TAGS: frozenset[str] = frozenset({
    "caimento_bom",
    "conforto_positivo",
    "feedback_positivo_geral",
    "modelagem_boa",
    "tamanho_ideal",
    "tecido_qualidade_boa",
})

LOGISTICA_TAGS: frozenset[str] = frozenset({
    "atendimento_ineficiente",
    "logistica_adiantamento",
    "logistica_atraso",
    "logistica_embalagem",
    "logistica_item_errado",
    "logistica_item_faltando",
    "provador_virtual_impreciso",
})

SINAL_DESCRICAO: dict[str, str] = {
    "Priorizar melhoria": "alta T&D e alta tração comercial",
    "Alerta em produto relevante": "produto relevante com T&D em escalada",
    "Monitorar": "alta T&D, baixa tração comercial",
    "Não priorizar agora": "sem urgência no momento",
    "Sem evidência suficiente": "volume insuficiente para diagnóstico",
}

# ---------------------------------------------------------------------------
# Workbook formatting constants (openpyxl)
# ---------------------------------------------------------------------------

_TAB_COLORS: dict[str, str] = {
    "farol_executivo": "4472C4",
    "resumo_farol": "70AD47",
    "benchmark_categoria": "9DC3E6",
    "resumo_tags": "9DC3E6",
    "priorizar_melhoria": "C00000",
    "tweets_analiticos": "C00000",
    "relatorio_pf": "ED7D31",
    "amostra_analitica": "A5A5A5",
}

_SINAL_ROW_COLORS: dict[str, str] = {
    "Priorizar melhoria": "FFD7D7",
    "Alerta em produto relevante": "FFF9D7",
    "Monitorar": "FFE8CC",
    "Não priorizar agora": "F2F2F2",
    "Sem evidência suficiente": "FFFFFF",
}


def validate_columns(
    df: pd.DataFrame,
    required_columns: Iterable[str],
    dataframe_name: str = "dataframe",
) -> None:
    """Raise a clear error if required columns are missing."""

    missing = sorted(set(required_columns) - set(df.columns))
    if missing:
        raise ValueError(
            f"{dataframe_name} is missing required columns: {', '.join(missing)}"
        )


def coerce_numeric(
    df: pd.DataFrame,
    columns: Sequence[str],
) -> pd.DataFrame:
    """Return a copy with selected columns converted to numeric values."""

    out = df.copy()
    for column in columns:
        if column in out.columns:
            out[column] = pd.to_numeric(out[column], errors="coerce")
    return out


def prepare_executive_df(df: pd.DataFrame) -> pd.DataFrame:
    """Validate and normalize the executive product-level dataframe."""

    validate_columns(df, EXECUTIVE_REQUIRED_COLUMNS, "executive_df")

    numeric_columns = [
        "priority_score",
        "td_score",
        "commercial_score",
        "qt_pedidos",
        "qt_skus",
        "qt_items_vendidos",
        "receita_liquida",
        "qt_reversas",
        "qt_items_returned",
        "qt_trocas",
        "qt_devolucoes",
        "valor_troca",
        "valor_devolucao",
        "td_rate",
        "td_rate_categoria",
        "delta_vs_categoria",
        "ratio_vs_categoria",
        "share_receita_portfolio",
        "share_unidades_portfolio",
        "share_td_portfolio",
        "top_1_pct",
        "top_2_pct",
        "top_3_pct",
        "pct_top_3_total",
        "principal_cor_pct",
        "principal_tamanho_pct",
        "reversas_ultimos_3m",
        "reversas_3m_anteriores",
        "qt_reversas_fisico",
        "qt_reversas_logistico",
    ]
    out = coerce_numeric(df, numeric_columns)

    sort_cols = ["priority_score", "qt_items_returned", "receita_liquida"]
    available_sort_cols = [c for c in sort_cols if c in out.columns]
    return out.sort_values(available_sort_cols, ascending=False).reset_index(drop=True)


def classify_priority(
    df: pd.DataFrame,
    thresholds: PrioritizationThresholds = PrioritizationThresholds(),
) -> pd.DataFrame:
    """Recompute prioritization labels in Python for QA or sensitivity tests."""

    out = prepare_executive_df(df)

    conditions = [
        (out["qt_items_vendidos"] < thresholds.min_items_vendidos)
        | (out["qt_items_returned"] < thresholds.min_items_returned),
        (out["td_score"] >= thresholds.td_score_prioritize)
        & (out["commercial_score"] >= thresholds.commercial_score_prioritize),
        (out["td_score"] >= thresholds.td_score_prioritize)
        & (out["commercial_score"] < thresholds.commercial_score_prioritize),
        (out["commercial_score"] >= thresholds.commercial_score_alert)
        & (out["td_score"] >= thresholds.td_score_alert_min)
        & (out["td_score"] < thresholds.td_score_prioritize),
        (out["td_score"] < thresholds.low_td_score)
        | (out["commercial_score"] < thresholds.low_commercial_score),
    ]
    labels = [
        "Sem evidência suficiente",
        "Priorizar melhoria",
        "Monitorar",
        "Alerta em produto relevante",
        "Não priorizar agora",
    ]

    out["sinal_priorizacao_python"] = np.select(conditions, labels, default="Monitorar")
    out["sinal_confere_sql"] = out["sinal_priorizacao_python"].eq(
        out["sinal_priorizacao"]
    )
    return out


def priority_summary(df: pd.DataFrame) -> pd.DataFrame:
    """Summarize portfolio impact by prioritization bucket."""

    out = prepare_executive_df(df)
    summary = (
        out.groupby("sinal_priorizacao", dropna=False)
        .agg(
            produtos=("product_name", "nunique"),
            unidades_vendidas=("qt_items_vendidos", "sum"),
            receita_liquida=("receita_liquida", "sum"),
            itens_retornados=("qt_items_returned", "sum"),
            td_rate_medio=("td_rate", "mean"),
            priority_score_medio=("priority_score", "mean"),
        )
        .reset_index()
    )
    total_revenue = summary["receita_liquida"].sum()
    total_returned = summary["itens_retornados"].sum()
    summary["share_receita"] = np.where(
        total_revenue > 0, summary["receita_liquida"] / total_revenue, 0
    )
    summary["share_itens_retornados"] = np.where(
        total_returned > 0, summary["itens_retornados"] / total_returned, 0
    )
    return summary.sort_values("itens_retornados", ascending=False).reset_index(drop=True)


def top_offenders(
    df: pd.DataFrame,
    bucket: str | None = "Priorizar melhoria",
    n: int = 20,
    min_items_returned: int = 5,
) -> pd.DataFrame:
    """Return top offender products ranked by priority score and returned items."""

    out = prepare_executive_df(df)
    if bucket is not None:
        out = out[out["sinal_priorizacao"].eq(bucket)]
    out = out[out["qt_items_returned"].fillna(0) >= min_items_returned]
    return out.sort_values(
        ["priority_score", "qt_items_returned", "td_rate"],
        ascending=[False, False, False],
    ).head(n)


def category_benchmark(df: pd.DataFrame) -> pd.DataFrame:
    """Aggregate product-level results by category for benchmarking."""

    out = prepare_executive_df(df)
    category = (
        out.groupby("category", dropna=False)
        .agg(
            produtos=("product_name", "nunique"),
            unidades_vendidas=("qt_items_vendidos", "sum"),
            receita_liquida=("receita_liquida", "sum"),
            itens_retornados=("qt_items_returned", "sum"),
            produtos_priorizar=(
                "sinal_priorizacao",
                lambda s: int((s == "Priorizar melhoria").sum()),
            ),
            td_rate_medio_produto=("td_rate", "mean"),
            td_rate_mediano_produto=("td_rate", "median"),
        )
        .reset_index()
    )
    category["td_rate_categoria_recalculado"] = np.where(
        category["unidades_vendidas"] > 0,
        category["itens_retornados"] / category["unidades_vendidas"],
        0,
    )
    return category.sort_values(
        ["produtos_priorizar", "itens_retornados"], ascending=False
    ).reset_index(drop=True)


def problema_tipo_split(df: pd.DataFrame) -> pd.DataFrame:
    """Breakdown T&D reversas by problem type (Físico / Logístico / Desistência).

    Uses the pre-aggregated qt_reversas_fisico and qt_reversas_logistico columns
    from the executive table.  The remainder (Outros + Desistência) is inferred
    as total reversas minus the two explicit buckets.
    """

    out = prepare_executive_df(df)
    total_reversas = float(out["qt_reversas"].fillna(0).sum())
    qt_fisico = (
        float(out["qt_reversas_fisico"].fillna(0).sum())
        if "qt_reversas_fisico" in out.columns
        else 0.0
    )
    qt_logistico = (
        float(out["qt_reversas_logistico"].fillna(0).sum())
        if "qt_reversas_logistico" in out.columns
        else 0.0
    )
    qt_outros = max(0.0, total_reversas - qt_fisico - qt_logistico)

    rows = [
        {"tipo_problema": "Físico", "qt_reversas": qt_fisico},
        {"tipo_problema": "Logístico", "qt_reversas": qt_logistico},
        {"tipo_problema": "Outros / Desistência", "qt_reversas": qt_outros},
    ]
    result = pd.DataFrame(rows)
    result["pct_total"] = result["qt_reversas"].div(
        total_reversas if total_reversas > 0 else 1.0
    )
    return result.sort_values("qt_reversas", ascending=False).reset_index(drop=True)


def tag_summary_from_executive(df: pd.DataFrame) -> pd.DataFrame:
    """Summarize top problem tags already pivoted in the executive table."""

    out = prepare_executive_df(df)
    frames = []
    for rank in (1, 2, 3):
        problem_col = f"top_{rank}_problema"
        pct_col = f"top_{rank}_pct"
        if problem_col in out.columns:
            tmp = out[["product_name", "sinal_priorizacao", problem_col, pct_col]].copy()
            tmp = tmp.rename(columns={problem_col: "problema_tag", pct_col: "pct_no_produto"})
            tmp["rank"] = rank
            frames.append(tmp)
    if not frames:
        return pd.DataFrame(columns=["problema_tag", "produtos", "pct_medio_no_produto"])

    long_df = pd.concat(frames, ignore_index=True)
    long_df = long_df.dropna(subset=["problema_tag"])
    return (
        long_df.groupby("problema_tag", dropna=False)
        .agg(
            produtos=("product_name", "nunique"),
            produtos_priorizar=(
                "sinal_priorizacao",
                lambda s: int((s == "Priorizar melhoria").sum()),
            ),
            pct_medio_no_produto=("pct_no_produto", "mean"),
        )
        .reset_index()
        .sort_values(["produtos_priorizar", "produtos"], ascending=False)
        .reset_index(drop=True)
    )


def validate_no_tag_duplication(
    analytical_df: pd.DataFrame,
    executive_df: pd.DataFrame,
    tolerance: float = 0.01,
) -> Mapping[str, float | bool]:
    """Check if analytical tag-level data would inflate returned item counts.

    This compares the executive returned-items total against a deduplicated
    analytical total by order_name + sku. It is a QA guardrail: the executive
    T&D numerator should not be built by summing tag rows.
    """

    validate_columns(analytical_df, ANALYTICAL_REQUIRED_COLUMNS, "analytical_df")
    executive = prepare_executive_df(executive_df)
    analytical = coerce_numeric(analytical_df, ["qt_items_returned"])

    dedup = analytical.drop_duplicates(["order_name", "sku"])
    analytical_total = float(dedup["qt_items_returned"].fillna(0).sum())
    executive_total = float(executive["qt_items_returned"].fillna(0).sum())
    diff = executive_total - analytical_total
    pct_diff = diff / executive_total if executive_total else 0.0

    return {
        "executive_total_returned": executive_total,
        "dedup_analytical_total_returned": analytical_total,
        "absolute_diff": diff,
        "pct_diff_vs_executive": pct_diff,
        "passes": abs(pct_diff) <= tolerance,
    }


def build_llm_context_rows(
    df: pd.DataFrame,
    only_buckets: Sequence[str] = (
        "Priorizar melhoria",
        "Alerta em produto relevante",
        "Monitorar",
    ),
    max_rows: int = 50,
) -> list[dict]:
    """Build compact product dictionaries to feed into an LLM summarizer."""

    out = prepare_executive_df(df)
    out = out[out["sinal_priorizacao"].isin(only_buckets)]
    out = out.sort_values("priority_score", ascending=False).head(max_rows)

    fields = [
        "product_name",
        "category",
        "gender",
        "portfolio_cluster",
        "sinal_priorizacao",
        "td_rate",
        "td_rate_categoria",
        "delta_vs_categoria",
        "qt_items_vendidos",
        "receita_liquida",
        "qt_items_returned",
        "qt_trocas",
        "qt_devolucoes",
        "qt_reversas_fisico",
        "qt_reversas_logistico",
        "commercial_score",
        "td_score",
        "priority_score",
        "top_1_problema",
        "top_1_pct",
        "top_2_problema",
        "top_2_pct",
        "top_3_problema",
        "top_3_pct",
        "pct_top_3_total",
        "principal_cor_afetada",
        "principal_cor_pct",
        "principal_tamanho_afetado",
        "principal_tamanho_pct",
        "tendencia_reversas",
        "comentarios_amostra",
        "resumo_pre_llm",
    ]
    available = [field for field in fields if field in out.columns]
    rows = out[available].replace({np.nan: None}).to_dict(orient="records")
    return rows


def create_product_summary_prompt(product_row: Mapping[str, object]) -> str:
    """Create a strict prompt for one product's qualitative summary."""

    return f"""
Você é uma analista de Produto/Físico da Insider Store.
Escreva um resumo curto, em um único parágrafo, sobre os problemas de T&D do produto abaixo.

Regras:
- Não invente causa.
- Só mencione cor ou tamanho se houver concentração informada.
- Só mencione tendência se houver evidência informada.
- Separe problema físico de problema logístico.
- Seja executivo e acionável.
- Máximo de 80 palavras.

Dados do produto:
{product_row}
""".strip()


def get_tipo_de_acao(top_1_tag: str | None) -> str:
    """Map the top-1 return tag to a recommended action type for the PF team.

    Returns one of: Modelagem, Grade, Tecido, PDP/Comunicação,
    Investigar tags negativas, Logístico — fora do escopo PF,
    or Investigação adicional.
    """
    if top_1_tag is None:
        return "Investigação adicional"
    if top_1_tag in POSITIVE_TAGS:
        return "Investigar tags negativas"
    if top_1_tag in LOGISTICA_TAGS:
        return "Logístico — fora do escopo PF"
    return TAG_TO_ACTION.get(top_1_tag, "Investigação adicional")


def build_tweet_heuristic(row: Mapping[str, object]) -> str:
    """Generate a rule-based ≤80-word analyst tweet for one product.

    Input is a product dict as produced by build_llm_context_rows().
    Covers: top-3 problems, color/size concentration (if ≥50%), T&D rate
    vs category, top-3 leverage, trend (if not stable), and suggested action.
    When Top 1 tag is positive, emits a disclaimer to investigate negative tags.
    """

    def _f(v: object) -> float | None:
        try:
            return float(v) if v is not None else None
        except (TypeError, ValueError):
            return None

    top_1_tag = row.get("top_1_problema")
    tipo_de_acao = get_tipo_de_acao(top_1_tag if isinstance(top_1_tag, str) else None)
    is_positive = isinstance(top_1_tag, str) and top_1_tag in POSITIVE_TAGS

    parts: list[str] = []

    # Positive tags disclaimer — replaces the offenders section
    if is_positive:
        parts.append(
            "⚠️ Tags predominantes são positivas. "
            "Recomenda-se investigar as tags negativas para diagnóstico completo."
        )
    else:
        # Top 3 problems
        tags: list[str] = []
        for rank in (1, 2, 3):
            tag = row.get(f"top_{rank}_problema")
            pct = _f(row.get(f"top_{rank}_pct"))
            if tag:
                suffix = f" ({pct:.0%})" if pct is not None else ""
                tags.append(f"{tag}{suffix}")
        if tags:
            parts.append(f"Ofensores: {', '.join(tags)}.")

    # Color concentration (≥50%)
    cor = row.get("principal_cor_afetada")
    cor_pct = _f(row.get("principal_cor_pct"))
    if cor and cor_pct is not None and cor_pct >= 0.50:
        parts.append(f"Cor crítica: {cor} ({cor_pct:.0%} das reversas).")

    # Size concentration (≥50%)
    tam = row.get("principal_tamanho_afetado")
    tam_pct = _f(row.get("principal_tamanho_pct"))
    if tam and tam_pct is not None and tam_pct >= 0.50:
        parts.append(f"Tamanho crítico: {tam} ({tam_pct:.0%} das reversas).")

    # T&D rate vs category
    td_rate = _f(row.get("td_rate"))
    td_cat = _f(row.get("td_rate_categoria"))
    if td_rate is not None and td_cat is not None:
        delta = td_rate - td_cat
        direction = "acima" if delta >= 0 else "abaixo"
        parts.append(
            f"T&D: {td_rate:.1%} produto vs {td_cat:.1%} categoria "
            f"({abs(delta):.1%}pp {direction})."
        )

    # Top-3 leverage
    pct_top3 = _f(row.get("pct_top_3_total"))
    if pct_top3 is not None:
        parts.append(f"Top 3 concentra {pct_top3:.0%} das reversas tagueadas.")

    # Trend (skip stable / insufficient)
    trend = row.get("tendencia_reversas")
    if trend and trend not in ("Estável", "Sem volume para tendência"):
        parts.append(f"Tendência recente: {trend}.")

    # Suggested action type
    parts.append(f"Ação sugerida: {tipo_de_acao}.")

    result = " ".join(parts)
    words = result.split()
    if len(words) > 80:
        result = " ".join(words[:80]) + "…"
    return result or "Dados insuficientes para síntese."


def build_scorecard_product_view(
    executive_df: pd.DataFrame,
    scorecard_df: pd.DataFrame,
    n: int = 50,
    only_buckets: Sequence[str] | None = None,
) -> pd.DataFrame:
    """Merge the executive T&D table with the portfolio scorecard pillars.

    Parameters
    ----------
    executive_df:
        Output of prepare_executive_df(). Must contain product_name, category,
        gender, td_rate, td_rate_categoria, top_N_problema/pct columns.
    scorecard_df:
        Must contain: product_name, cluster, score_tracao_comercial,
        score_unit_economics, score_satisfacao_marca,
        td_produto_pct, td_categoria_pct.
    n:
        Max rows returned, sorted by priority_score DESC.
    only_buckets:
        If provided, filter to these sinal_priorizacao values before merging.
    """

    exec_out = prepare_executive_df(executive_df)
    if only_buckets is not None:
        exec_out = exec_out[exec_out["sinal_priorizacao"].isin(only_buckets)]

    merged = exec_out.merge(
        scorecard_df[
            [
                "product_name",
                "cluster",
                "score_tracao_comercial",
                "score_unit_economics",
                "score_satisfacao_marca",
                "td_produto_pct",
                "td_categoria_pct",
            ]
        ],
        on="product_name",
        how="left",
    )

    # Build "Top 3 motivos" string from pivoted columns already in executive_df
    def _top3_str(row: pd.Series) -> str:
        parts = []
        for rank in (1, 2, 3):
            tag = row.get(f"top_{rank}_problema")
            pct = row.get(f"top_{rank}_pct")
            if pd.isna(tag) or tag is None:
                continue
            pct_str = f"{pct:.0%}" if pd.notna(pct) else ""
            parts.append(f"{rank}. {tag} ({pct_str})")
        return "<br>".join(parts) if parts else "—"

    merged["top_3_motivos_td"] = merged.apply(_top3_str, axis=1)
    merged["tweet_analitico"] = merged.apply(build_tweet_heuristic, axis=1)

    cols = [
        "product_name",
        "category",
        "gender",
        "cluster",
        "sinal_priorizacao",
        "td_score",
        "score_tracao_comercial",
        "score_unit_economics",
        "score_satisfacao_marca",
        "td_categoria_pct",
        "td_produto_pct",
        "td_rate",
        "td_rate_categoria",
        "tendencia_reversas",
        "top_3_motivos_td",
        "tweet_analitico",
        "priority_score",
        "qt_items_returned",
        "receita_liquida",
    ]
    available = [c for c in cols if c in merged.columns]
    return (
        merged[available]
        .sort_values("priority_score", ascending=False)
        .head(n)
        .reset_index(drop=True)
    )


def build_mensagem_consolidada(row: Mapping[str, object]) -> str:
    """Build the consolidated 3-line message for the tweets_analiticos tab.

    Format:
        {product} - Sinal: {bucket} ({descrição})
        Top 3 problemas: {tag1}, {tag2} e {tag3}
        Tweet: {resumo analítico}
    """
    product = str(row.get("product_name") or "—")
    sinal = str(row.get("sinal_priorizacao") or "—")
    sinal_desc = SINAL_DESCRICAO.get(sinal, sinal.lower())

    tags: list[str] = []
    for rank in (1, 2, 3):
        tag = row.get(f"top_{rank}_problema")
        if tag and str(tag) not in ("nan", "None", ""):
            tags.append(str(tag))

    if len(tags) >= 3:
        tags_str = f"{tags[0]}, {tags[1]} e {tags[2]}"
    elif len(tags) == 2:
        tags_str = f"{tags[0]} e {tags[1]}"
    elif len(tags) == 1:
        tags_str = tags[0]
    else:
        tags_str = "sem tags disponíveis"

    tweet = str(row.get("tweet_analitico") or row.get("tweet_analista") or "—")

    return (
        f"{product} - Sinal: {sinal} ({sinal_desc})\n"
        f"Top 3 problemas: {tags_str}\n"
        f"Tweet: {tweet}"
    )


def _apply_workbook_formatting(wb: object) -> None:
    """Apply professional formatting to all sheets: header colors, tab colors,
    row coloring by sinal_priorizacao, freeze pane, and column widths."""
    from openpyxl.styles import Font, PatternFill, Alignment
    from openpyxl.utils import get_column_letter

    header_fill = PatternFill("solid", fgColor="1F497D")
    header_font = Font(bold=True, color="FFFFFF", name="Arial", size=10)
    body_font = Font(name="Arial", size=10)

    for ws in wb.worksheets:  # type: ignore[attr-defined]
        name = ws.title

        # Tab color
        color = _TAB_COLORS.get(name)
        if color:
            ws.sheet_properties.tabColor = color

        # Freeze top row
        ws.freeze_panes = "A2"
        ws.row_dimensions[1].height = 28

        # Identify key columns
        sinal_col_idx: int | None = None
        mensagem_col_idx: int | None = None
        for cell in ws[1]:
            if cell.value == "sinal_priorizacao":
                sinal_col_idx = cell.column
            if cell.value == "mensagem_consolidada":
                mensagem_col_idx = cell.column

        # Header row
        for cell in ws[1]:
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

        # Body: font + row coloring + alignment
        for row_idx, row in enumerate(ws.iter_rows(min_row=2), start=2):
            sinal_val = row[sinal_col_idx - 1].value if sinal_col_idx else None
            row_fill = None
            if sinal_val and str(sinal_val) in _SINAL_ROW_COLORS:
                row_fill = PatternFill("solid", fgColor=_SINAL_ROW_COLORS[str(sinal_val)])
            for cell in row:
                cell.font = body_font
                if row_fill:
                    cell.fill = row_fill
                if mensagem_col_idx and cell.column == mensagem_col_idx:
                    cell.alignment = Alignment(wrap_text=True, vertical="top")
                else:
                    cell.alignment = Alignment(vertical="center")
            if name == "tweets_analiticos":
                ws.row_dimensions[row_idx].height = 90

        # Column widths
        wide_cols = {"mensagem_consolidada", "tweet_analitico", "top_3_motivos_td", "comentarios_amostra"}
        medium_cols = {"product_name", "resumo_pre_llm"}
        for col in ws.columns:
            hdr = str(col[0].value or "")
            letter = get_column_letter(col[0].column)
            if hdr == "mensagem_consolidada":
                ws.column_dimensions[letter].width = 90
            elif hdr in wide_cols:
                ws.column_dimensions[letter].width = 60
            elif hdr in medium_cols:
                ws.column_dimensions[letter].width = 35
            else:
                max_len = max((len(str(c.value or "")) for c in col), default=8)
                ws.column_dimensions[letter].width = min(max(max_len + 2, 10), 32)


def build_tweets_tab(
    executive_df: pd.DataFrame,
    buckets: Sequence[str] = ("Priorizar melhoria", "Alerta em produto relevante"),
) -> pd.DataFrame:
    """Build the tweets_analiticos tab — one actionable tweet per product.

    Filtered to action buckets only (default: Priorizar melhoria + Alerta em
    produto relevante). Sorted by bucket priority then priority_score DESC.

    Primary column is ``mensagem_consolidada``: a 3-line block with product
    name + sinal description, Top 3 problems, and the analytical tweet.
    """
    out = prepare_executive_df(executive_df)
    out = out[out["sinal_priorizacao"].isin(buckets)].copy()

    out["tipo_de_acao"] = out["top_1_problema"].apply(
        lambda t: get_tipo_de_acao(t if isinstance(t, str) else None)
    )
    out["tweet_analitico"] = out.apply(build_tweet_heuristic, axis=1)
    out["mensagem_consolidada"] = out.apply(build_mensagem_consolidada, axis=1)

    if "portfolio_cluster" in out.columns:
        out = out.rename(columns={"portfolio_cluster": "cluster"})

    bucket_order = {b: i for i, b in enumerate(buckets)}
    out["_bucket_order"] = out["sinal_priorizacao"].map(bucket_order).fillna(99)
    out = (
        out.sort_values(["_bucket_order", "priority_score"], ascending=[True, False])
        .drop(columns=["_bucket_order"])
        .reset_index(drop=True)
    )

    cols = [
        "product_name",
        "sinal_priorizacao",
        "mensagem_consolidada",
        "tipo_de_acao",
        "category",
        "gender",
        "cluster",
        "td_rate",
        "td_rate_categoria",
        "tendencia_reversas",
        "priority_score",
    ]
    available = [c for c in cols if c in out.columns]
    return out[available]


def export_priority_workbook(
    executive_df: pd.DataFrame,
    output_path: str,
    analytical_df: pd.DataFrame | None = None,
    scorecard_view_df: pd.DataFrame | None = None,
    tweets_df: pd.DataFrame | None = None,
) -> None:
    """Export core analysis tabs to an Excel workbook.

    Tab order: farol_executivo, resumo_farol, benchmark_categoria, resumo_tags,
    priorizar_melhoria, tweets_analiticos (if provided), relatorio_pf (if provided),
    amostra_analitica (if provided).
    """

    executive = prepare_executive_df(executive_df)
    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        executive.to_excel(writer, sheet_name="farol_executivo", index=False)
        priority_summary(executive).to_excel(writer, sheet_name="resumo_farol", index=False)
        category_benchmark(executive).to_excel(writer, sheet_name="benchmark_categoria", index=False)
        tag_summary_from_executive(executive).to_excel(writer, sheet_name="resumo_tags", index=False)
        top_offenders(executive, bucket="Priorizar melhoria", n=50).to_excel(
            writer, sheet_name="priorizar_melhoria", index=False
        )
        if tweets_df is not None:
            tweets_df.to_excel(writer, sheet_name="tweets_analiticos", index=False)
        if scorecard_view_df is not None:
            scorecard_view_df.to_excel(writer, sheet_name="relatorio_pf", index=False)
        if analytical_df is not None:
            analytical_df.head(100000).to_excel(writer, sheet_name="amostra_analitica", index=False)
        _apply_workbook_formatting(writer.book)
